name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/valkolaci/mayastor:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
